/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalkamera;

/**
 *
 * @author I Dewa Made Putra Kumara
 * 2024-06-29
 */
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class RentalKameraFrame extends javax.swing.JFrame {

    /**
     * Creates new form RentalKameraFrame
     */
    public RentalKameraFrame() {
        initComponents();
        
        
        ButtonGroup buttonGroupJenisKelamin = new ButtonGroup();
        buttonGroupJenisKelamin.add(rblaki);
        buttonGroupJenisKelamin.add(rbperempuan);
        
//        // Inisialisasi model tabel dengan kolom-kolom yang sesuai
//        String[] columnNames = {"ID", "Nama", "Jenis Kelamin", "Alamat", "Kamera", "Tambahan", "Tgl Sewa", "Tgl Kembali", "Pembayaran", "Total Hari", "Total Harga"};
//        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
//
//        // Inisialisasi tabel dengan model tabel yang sudah dibuat
//        tabel_data.setModel(tableModel);
//
//        // Tambahkan tabel ke JScrollPane dan tambahkan JScrollPane ke layout
//        JScrollPane scrollPane = new JScrollPane(tabel_data);
//        getContentPane().add(scrollPane, BorderLayout.CENTER);
        
        load_tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        btntambah = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listkamera = new javax.swing.JList<>();
        cbbaterai = new javax.swing.JCheckBox();
        cbsdcard = new javax.swing.JCheckBox();
        cbtripod = new javax.swing.JCheckBox();
        combobayar = new javax.swing.JComboBox<>();
        txttotalhari = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtalamat = new javax.swing.JTextField();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        datekembali = new com.toedter.calendar.JDateChooser();
        datesewa = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jenis Kelamin", "Alamat", "Kamera", "Tambahan", "Tanggal Sewa", "Tanggal Kembali", "Pembayaran", "Total Hari"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_data);

        btntambah.setBackground(new java.awt.Color(204, 255, 204));
        btntambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btntambah.setText("TAMBAH");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(255, 255, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedit.setText("UBAH");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 153, 153));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEWA KAMERA UTAMA MANDIRI");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KARTU IDENTITAS :");

        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NAMA :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JENIS KELAMIN :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ALAMAT :");

        rblaki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rblaki.setText("Laki - Laki");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });

        rbperempuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbperempuan.setText("Perempuan");
        rbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbperempuanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("KAMERA :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("TAMBAHAN :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TANGGAL SEWA :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("TANGGAL KEMBALI :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PEMBAYARAN :");

        listkamera.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listkamera.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Canon EOS 5D Mark IV", "Nikon D850", "Sony Alpha A7 III", "Panasonic Lumix GH5", "Fujifilm X-T4", "Canon EOS R5", "Blackmagic Pocket Cinema Camera 6K" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listkamera);

        cbbaterai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbaterai.setText("Baterai");
        cbbaterai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbateraiActionPerformed(evt);
            }
        });

        cbsdcard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbsdcard.setText("SD Card");

        cbtripod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbtripod.setText("Tripod");
        cbtripod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtripodActionPerformed(evt);
            }
        });

        combobayar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combobayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "BRI", "BCA", " " }));
        combobayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobayarActionPerformed(evt);
            }
        });

        txttotalhari.setEditable(false);
        txttotalhari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txttotalhari.setText("total hari akan muncul saat data ditambah");
        txttotalhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalhariActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("TOTAL HARI :");

        txtalamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatActionPerformed(evt);
            }
        });

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        btncari.setBackground(new java.awt.Color(204, 204, 204));
        btncari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CARI NAMA :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncari))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rbperempuan)
                                            .addGap(77, 77, 77)
                                            .addComponent(rblaki))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel13))
                                    .addGap(87, 87, 87)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(cbbaterai)
                                                .addGap(40, 40, 40)
                                                .addComponent(cbsdcard)
                                                .addGap(44, 44, 44)
                                                .addComponent(cbtripod))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel15))
                                    .addGap(40, 40, 40)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(combobayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txttotalhari)
                                        .addComponent(datekembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datesewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(63, 63, 63)
                                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(datesewa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(datekembali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rblaki)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbperempuan)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(combobayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txttotalhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbaterai)
                    .addComponent(cbsdcard)
                    .addComponent(cbtripod)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addComponent(btncari, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbtripodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtripodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtripodActionPerformed

    private void cbbateraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbateraiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbateraiActionPerformed

    private void combobayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobayarActionPerformed

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblakiActionPerformed

    private void rbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbperempuanActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        try {
        String sql = "INSERT INTO penyewa (id, nama, jenis_kelamin, alamat, kamera, tambahan, tgl_sewa, tgl_kembali, pembayaran, total_hari) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, txtid.getText());
        pst.setString(2, txtnama.getText());
        
        String jenisKelamin;
        if (rblaki.isSelected()) {
            jenisKelamin = "Laki-laki";
        } else if (rbperempuan.isSelected()) {
            jenisKelamin = "Perempuan";
        } else {
            jenisKelamin = ""; // Atau nilai default lainnya
        }
        
        pst.setString(3, jenisKelamin);
        pst.setString(4, txtalamat.getText());
        
        String kamera = listkamera.getSelectedValue();
            pst.setString(5, kamera);

        StringBuilder tambahan = new StringBuilder();
            if (cbbaterai.isSelected()) tambahan.append("Baterai ");
            if (cbtripod.isSelected()) tambahan.append("Tripod ");
            if (cbsdcard.isSelected()) tambahan.append("SD Card");
            pst.setString(6, tambahan.toString().trim());

            // Get dates from JDateChooser
        java.util.Date tglSewa = datesewa.getDate();
        java.util.Date tglKembali = datekembali.getDate();
        pst.setDate(7, new java.sql.Date(tglSewa.getTime()));
        pst.setDate(8, new java.sql.Date(tglKembali.getTime()));
        pst.setString(9, combobayar.getSelectedItem().toString());
            
        long diff = tglKembali.getTime() - tglSewa.getTime();
            int totalHari = (int) (diff / (1000 * 60 * 60 * 24));
            txttotalhari.setText(String.valueOf(totalHari));
            pst.setInt(10, totalHari);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        load_tabel();
        
        // Tutup PreparedStatement dan Connection
        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
 

        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "UPDATE penyewa SET nama=?, jenis_kelamin=?, alamat=?, kamera=?, tambahan=?, tgl_sewa=?, tgl_kembali=?, pembayaran=?, total_hari=? WHERE id=?";
            java.sql.Connection conn = koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, txtnama.getText());

            String jenisKelamin;
            if (rblaki.isSelected()) {
                jenisKelamin = "Laki-laki";
            } else if (rbperempuan.isSelected()) {
                jenisKelamin = "Perempuan";
            } else {
                jenisKelamin = ""; // Atau nilai default lainnya
            }
            pst.setString(2, jenisKelamin);

            pst.setString(3, txtalamat.getText());

            String kamera = listkamera.getSelectedValue();
            pst.setString(4, kamera);

            StringBuilder tambahan = new StringBuilder();
            if (cbbaterai.isSelected()) tambahan.append("Baterai ");
            if (cbtripod.isSelected()) tambahan.append("Tripod ");
            if (cbsdcard.isSelected()) tambahan.append("SD Card");
            pst.setString(5, tambahan.toString().trim());

            // Get dates from JDateChooser
            java.util.Date tglSewa = datesewa.getDate();
            java.util.Date tglKembali = datekembali.getDate();
            if (tglSewa != null) {
                pst.setDate(6, new java.sql.Date(tglSewa.getTime()));
            } else {
                pst.setNull(6, java.sql.Types.DATE);
            }
            if (tglKembali != null) {
                pst.setDate(7, new java.sql.Date(tglKembali.getTime()));
            } else {
                pst.setNull(7, java.sql.Types.DATE);
            }

            pst.setString(8, combobayar.getSelectedItem().toString());
            
            long diff = tglKembali.getTime() - tglSewa.getTime();
            int totalHari = (int) (diff / (1000 * 60 * 60 * 24));
            txttotalhari.setText(String.valueOf(totalHari));
            pst.setInt(9, totalHari);
            pst.setString(10, txtid.getText());
            
            

            int affectedRows = pst.executeUpdate();
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                load_tabel(); // Refresh the table to show updated data
            } else {
                JOptionPane.showMessageDialog(null, "Gagal mengubah data. ID tidak ditemukan");
            }

            // Tutup PreparedStatement dan Connection
            pst.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
}

        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try {
            // Mendapatkan indeks baris yang dipilih
            int rowIndex = tabel_data.getSelectedRow();

            // Memastikan bahwa baris telah dipilih
            if (rowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus");
                return;
            }

            // Mendapatkan nilai ID dari baris yang dipilih
            String id = tabel_data.getValueAt(rowIndex, 0).toString();

            // Konfirmasi penghapusan
            int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Query SQL untuk menghapus data
                String sql = "DELETE FROM penyewa WHERE id=?";
                java.sql.Connection conn = koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);

                // Eksekusi query hapus
                int rowsDeleted = pst.executeUpdate();

                // Menampilkan pesan berhasil atau gagal
                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    load_tabel(); // Refresh the table to show updated data
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data");
                }

                // Menutup PreparedStatement dan Connection
                pst.close();
                conn.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
}

        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txttotalhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalhariActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
        
        int rowIndex = tabel_data.getSelectedRow();
        // Mengambil nilai dari kolom yang sesuai dengan baris yang diklik
        String id = tabel_data.getValueAt(rowIndex, 0).toString();
        String nama = tabel_data.getValueAt(rowIndex, 1).toString();
        String jenisKelamin = tabel_data.getValueAt(rowIndex, 2).toString();
        String alamat = tabel_data.getValueAt(rowIndex, 3).toString();
        String kamera = tabel_data.getValueAt(rowIndex, 4).toString();
        String tambahan = tabel_data.getValueAt(rowIndex, 5).toString();
        String tglSewa = tabel_data.getValueAt(rowIndex, 6).toString();
        String tglKembali = tabel_data.getValueAt(rowIndex, 7).toString();
        String pembayaran = tabel_data.getValueAt(rowIndex, 8).toString();
        String totalHari = tabel_data.getValueAt(rowIndex, 9).toString();

        // Menampilkan nilai dari kolom yang sesuai ke dalam elemen input
        txtid.setText(id);
        txtnama.setText(nama);
        txtalamat.setText(alamat);

        if (jenisKelamin.equals("Laki-laki")) {
            rblaki.setSelected(true);
        } else if (jenisKelamin.equals("Perempuan")) {
            rbperempuan.setSelected(true);
        } else {
            // Reset radio buttons if gender is not recognized
            buttonGroupJenisKelamin.clearSelection();
        }

        // Menetapkan nilai pada list kamera
        listkamera.setSelectedValue(kamera, true);

        // Menetapkan nilai pada checkboxes tambahan
        cbbaterai.setSelected(tambahan.contains("Baterai"));
        cbtripod.setSelected(tambahan.contains("Tripod"));
        cbsdcard.setSelected(tambahan.contains("SD Card"));

        // Menetapkan nilai pada JDateChooser
        try {
            java.util.Date sewaDate = new SimpleDateFormat("yyyy-MM-dd").parse(tglSewa);
            datesewa.setDate(sewaDate);
            java.util.Date kembaliDate = new SimpleDateFormat("yyyy-MM-dd").parse(tglKembali);
            datekembali.setDate(kembaliDate);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        // Menetapkan nilai pada combobox pembayaran
        combobayar.setSelectedItem(pembayaran);

        txttotalhari.setText(totalHari);
                
        
        
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void txtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        // Ambil teks pencarian dari JTextField txtcari
    String searchTerm = txtcari.getText();
    
    try {
        String sql = "SELECT * FROM penyewa WHERE nama LIKE ?";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, "%" + searchTerm + "%");

        ResultSet rs = pst.executeQuery();

        // Clear existing rows in the table model
        DefaultTableModel tableModel = (DefaultTableModel) tabel_data.getModel();
        tableModel.setRowCount(0); // Menghapus semua baris yang ada

        while (rs.next()) {
            String id = rs.getString("id");
            String nama = rs.getString("nama");
            String jenisKelamin = rs.getString("jenis_kelamin");
            String alamat = rs.getString("alamat");
            String kamera = rs.getString("kamera");
            String tambahan = rs.getString("tambahan");
            Date tglSewa = rs.getDate("tgl_sewa");
            Date tglKembali = rs.getDate("tgl_kembali");
            String pembayaran = rs.getString("pembayaran");
            int totalHari = rs.getInt("total_hari");

            // Create row object array
            Object[] row = {id, nama, jenisKelamin, alamat, kamera, tambahan, tglSewa, tglKembali, pembayaran, totalHari};

            // Add row to table model
            tableModel.addRow(row);
        }

        pst.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btncariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalKameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalKameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalKameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalKameraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalKameraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbbaterai;
    private javax.swing.JCheckBox cbsdcard;
    private javax.swing.JCheckBox cbtripod;
    private javax.swing.JComboBox<String> combobayar;
    private com.toedter.calendar.JDateChooser datekembali;
    private com.toedter.calendar.JDateChooser datesewa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listkamera;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotalhari;
    // End of variables declaration//GEN-END:variables
    
    private ButtonGroup buttonGroupJenisKelamin;
    private void load_tabel() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nama");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Alamat");
    model.addColumn("Kamera");
    model.addColumn("Tambahan");
    model.addColumn("Tanggal Sewa");
    model.addColumn("Tanggal Kembali");
    model.addColumn("Pembayaran");
    model.addColumn("Total Hari");

    // Menampilkan data database ke dalam tabel
    try {
        int id = 1;
        String sql = "SELECT * FROM penyewa";
        java.sql.Connection conn = koneksi.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while (res.next()) {
            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10)});
        }
        
        tabel_data.setModel(model);
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }
    
}
